### ISSUE TITLE
mongoengine.connection.ConnectionFailure: You have not defined a default connection

### ISSUE THREAD

**Issue by moriweiji** [watzon/telethon-session-mongo#1]
Excuse me, why do I keep reporting “mongoengine.connection.ConnectionFailure: You have not defined a default connection”errors?

**Comment by watzon** [comment]
What does your config look like?

**Comment by mmuniz75** [comment]
I have the same issue on Python 3.7.7

My conection code is :
host = "mongodb://localhost/telethon"
session = MongoSession(phone, host=host)
client = TelegramClient(session, API_ID, API_HASH)

my config is :
![image](https://user-images.githubusercontent.com/22776932/81341944-cbf4ee00-9088-11ea-8bdf-7be9dd148ab5.png)

**Comment by watzon** [comment]
Sorry I need to update the readme. This expects you to use `mongoengine` to create a connection. Something like:

```python
MONGO_DB = "telethon"
MONGO_URI = f"mongodb://localhost/{MONGO_DB}"
mongoengine.connect(MONGO_DB, host=MONGO_URI)
session = MongoSession(MONGO_DB, host=MONGO_URI)
client = TelegramClient(session, API_ID, API_HASH)
```

**Comment by mmuniz75** [comment]
> Sorry I need to update the readme. This expects you to use `mongoengine` to create a connection. Something like:
> 
> ```python
> MONGO_DB = "telethon"
> MONGO_URI = f"mongodb://localhost/{MONGO_DB}"
> mongoengine.connect(MONGO_DB, host=MONGO_URI)
> session = MongoSession(MONGO_DB, host=MONGO_URI)
> client = TelegramClient(session, API_ID, API_HASH)
> ```

Thank's it works, for future references need add : from mongoengine import connect

A limitation that I see is that there is no set for multiple sessions, all new login replace the current Session. On SQLALquemy version we set a session, so  multiples sessions can be store in database.

**Comment by watzon** [comment]
I based it off the SQLite version, but I'd be happy for a PR if that's something you want to add

**Comment by mrworksome** [comment]
> Sorry I need to update the readme. This expects you to use `mongoengine` to create a connection. Something like:
> 
> ```python
> MONGO_DB = "telethon"
> MONGO_URI = f"mongodb://localhost/{MONGO_DB}"
> mongoengine.connect(MONGO_DB, host=MONGO_URI)
> session = MongoSession(MONGO_DB, host=MONGO_URI)
> client = TelegramClient(session, API_ID, API_HASH)
> ```

Hi, it work, but not updated in readmy)
Thanks, for this library))

**Comment by watzon** [comment]
If anyone wants to PR I'd be happy to merge. Just been really busy and haven't been using this myself.

**Comment by watzon** [comment]
Fixed this in the README
