### ISSUE TITLE
Multiple accounts support

### ISSUE THREAD

**Issue by rewiaca** [watzon/telethon-session-mongo#3]
Hi Chris @watzon! 
Does your code support account switching?

**Comment by watzon** [comment]
Maybe, I don't know. I based it off the official SQLite code, so if that supports account switching then I suppose this should too.

**Comment by watzon** [comment]
Thinking about this a bit further, there's no reason this couldn't support multiple accounts, but each would need to use a separate database and TelegramClient instance.
